# Generated by Django 3.2.8 on 2021-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Nickname')),
                ('email', models.CharField(max_length=50, verbose_name='Email-address')),
                ('product', models.CharField(max_length=30, verbose_name='Products')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
