# Generated by Django 3.2.8 on 2021-11-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product-name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('company', models.CharField(max_length=30, verbose_name='Company')),
            ],
        ),
    ]
